name: sloti_co
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  animate_do: ^3.3.4
  change_app_package_name: ^1.5.0
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_imagekit: ^0.0.6
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.10
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  pull_to_refresh_flutter3: ^2.0.2
  shared_preferences: ^2.3.5
  syncfusion_flutter_charts: ^28.2.4+1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
   - asset/images/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/images/appIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
